---
title: "Homework 5"
author: Adarsh Ramakrishnan
output: github_document
---

This is my homework 5 solution:


Loading libraries:

```{r libraries}
library(tidyverse)
```


## Problem 1

Load the homicide dataset - 


```{r}
homicide_df = read_csv("./data/homicide-data.csv")%>% 
janitor::clean_names()
```

Let us now create city_state variable and resolved variable

```{r}
homicide_df = 
  
  homicide_df%>%
  mutate(city_state = str_c(city,", ", state))%>%
  mutate(resolved = case_when(
        disposition == 'Closed without arrest' ~   "unsolved",
        disposition == 'Open/No arrest' ~ "unsolved",
        disposition == 'Closed by arrest' ~ "solved"))   %>%
  select(city_state, resolved)%>%
  filter(city_state != "Tulsa_AL")
```

Group by and summarize to get total number of cases per city and number of unsolved cases

```{r}
homicide_aggregare_df = 
  
  homicide_df%>%
  group_by(city_state)%>%
  summarize(
    total_hom = n(),
    unsolved_hom = sum(resolved == "unsolved")
  )
```

Using the prop test for a single city

```{r}
prop.test(
homicide_aggregare_df%>%filter(city_state == "Baltimore, MD")%>% pull(unsolved_hom),
homicide_aggregare_df%>%filter(city_state == "Baltimore, MD")%>% pull(total_hom) 
)%>%
  broom::tidy()
```


Iteration..


```{r}
results_df =
  homicide_aggregare_df%>%
  mutate(
    prop_tests = map2(.x = unsolved_hom, .y = total_hom, ~prop.test(x = .x, n = .y)),
tidy_tests = map(.x = prop_tests, ~broom::tidy(.x))    
    
  )%>%
  
  select(-prop_tests)%>%
  unnest(tidy_tests)%>%
  select(city_state, estimate, conf.low, conf.high)
```


```{r}
results_df %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

## Problem 2

```{r}

```


